export enum WebSocketTopic {
  CHAT = "chat",
  COUNTER = "counter",

  // machines
  CM_STATUS = "CM_STATUS",
  CM_USER_MSG = "CM_USER_MSG",
  CM_PRODUCT_ACTIVE = "CM_PRODUCT_ACTIVE",
  CM_PRODUCTS_DISABLED = "CM_PRODUCTS_DISABLED",
  GUI_READ_STATUS = "GUI_READ_STATUS",
  GUI_PRODUCT_START = "GUI_PRODUCT_START",
  GUI_PRODUCT_STOP = "GUI_PRODUCT_STOP",
  GUI_MSG_COMMAND = "GUI_MSG_COMMAND",
}
